export const MEDIA_RUNTIME_CONFIG = Symbol('MEDIA_RUNTIME_CONFIG');
export const DOCUMENT_STORAGE_PROVIDER = Symbol('DOCUMENT_STORAGE_PROVIDER');
export const VIDEO_PROVIDER = Symbol('VIDEO_PROVIDER');
